name: CI/CD - Deploy ML Project to Azure

on:
  push:
    branches:
      - main  # runs on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ Run tests (optional but recommended)
    - name: Run Tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    # 5️⃣ Login to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 6️⃣ Deploy to Azure Web App
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "your-app-service-name"  # Change this to your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
